name: R-CMD-check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::renv
          needs: check
      - name: Install dependencies (renv if lock exists)
        run: |
          if [ -f renv.lock ]; then R -q -e "renv::restore()"
          else echo "No renv.lock; skipping renv::restore()"
          fi
      - name: Run scripts (sanity)
        run: |
          R -q -e "source('R/01_data_prep.R')"