# Config for Political Trust project
data_file: "data/ess_political_trust.xlsx"   # put your file into data/ and update name if needed
seed: 123
psm:
  caliper: 0.1
  method: "nearest"
  distance: "logit"
models:
  rf_ntree: 500
  tree_cp: 0.015
  threshold: 0.5